version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.4.0
    container_name: "verdaccio-test"
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "81:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
networks:
  node-network:
    driver: bridge